import os
import numpy as np
import torch as T
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


class AgentQNetwork(nn.Module):
    """Per-agent Q-network. Input: local obs + local action. Output: Q-value."""
    def __init__(self, lr, input_dims, fc1_dims, fc2_dims, n_actions, agent_id,
                 chkpt_dir='tmp/ddpg'):
        super(AgentQNetwork, self).__init__()
        self.input_dims = input_dims + n_actions  # obs + action
        self.fc1_dims = fc1_dims
        self.fc2_dims = fc2_dims
        self.agent_id = agent_id
        self.name = f'agent_q_{agent_id}'
        self.checkpoint_dir = os.path.join(os.path.dirname(os.path.realpath(__file__)), chkpt_dir)
        self.checkpoint_file = os.path.join(self.checkpoint_dir, self.name)

        self.fc1 = nn.Linear(self.input_dims, fc1_dims)
        self.fc2 = nn.Linear(fc1_dims, fc2_dims)
        self.q = nn.Linear(fc2_dims, 1)

        self.bn1 = nn.LayerNorm(fc1_dims)
        self.bn2 = nn.LayerNorm(fc2_dims)

        self.optimizer = optim.Adam(self.parameters(), lr=lr)
        self.device = T.device('cuda:0' if T.cuda.is_available() else 'cpu')
        self.to(self.device)

    def forward(self, obs, action):
        x = T.cat([obs, action], dim=-1)
        x = F.relu(self.bn1(self.fc1(x)))
        x = F.relu(self.bn2(self.fc2(x)))
        q = self.q(x)
        return q

    def save_checkpoint(self):
        T.save(self.state_dict(), self.checkpoint_file)

    def load_checkpoint(self):
        self.load_state_dict(T.load(self.checkpoint_file))


class AgentTargetQNetwork(AgentQNetwork):
    """Target Q-network for an agent."""
    def __init__(self, lr, input_dims, fc1_dims, fc2_dims, n_actions, agent_id,
                 chkpt_dir='tmp/ddpg'):
        super().__init__(lr, input_dims, fc1_dims, fc2_dims, n_actions, agent_id, chkpt_dir)
        self.name = f'target_agent_q_{agent_id}'
        self.checkpoint_file = os.path.join(self.checkpoint_dir, self.name)


class AgentPolicyNetwork(nn.Module):
    """Policy network for each agent. Input: local obs. Output: action (tanh)."""
    def __init__(self, lr, input_dims, fc1_dims, fc2_dims, n_actions, agent_id,
                 chkpt_dir='tmp/ddpg'):
        super(AgentPolicyNetwork, self).__init__()
        self.fc1 = nn.Linear(input_dims, fc1_dims)
        self.fc2 = nn.Linear(fc1_dims, fc2_dims)
        self.mu = nn.Linear(fc2_dims, n_actions)

        self.bn1 = nn.LayerNorm(fc1_dims)
        self.bn2 = nn.LayerNorm(fc2_dims)

        self.name = f'policy_{agent_id}'
        self.checkpoint_dir = os.path.join(os.path.dirname(os.path.realpath(__file__)), chkpt_dir)
        self.checkpoint_file = os.path.join(self.checkpoint_dir, self.name)

        self.optimizer = optim.Adam(self.parameters(), lr=lr)
        self.device = T.device('cuda:0' if T.cuda.is_available() else 'cpu')
        self.to(self.device)

    def forward(self, obs):
        x = F.relu(self.bn1(self.fc1(obs)))
        x = F.relu(self.bn2(self.fc2(x)))
        return T.tanh(self.mu(x))

    def save_checkpoint(self):
        T.save(self.state_dict(), self.checkpoint_file)

    def load_checkpoint(self):
        self.load_state_dict(T.load(self.checkpoint_file))


class QMIXMixer(nn.Module):
    """
    Monotonic mixing network.
    Takes per-agent Q-values and global state, outputs a single global Q-value.
    Weights are generated by hypernetworks and constrained to be non-negative
    (via absolute value), ensuring monotonicity: dQ_tot/dQ_i >= 0.
    """
    def __init__(self, n_agents, state_dim, mix_embed_dim=32, chkpt_dir='tmp/ddpg'):
        super(QMIXMixer, self).__init__()
        self.n_agents = n_agents
        self.state_dim = state_dim

        # Hypernetwork for first layer weights and bias
        self.hyper_w1 = nn.Sequential(
            nn.Linear(state_dim, mix_embed_dim * n_agents),
            nn.ReLU(),
            nn.Linear(mix_embed_dim * n_agents, mix_embed_dim * n_agents),
        )
        self.hyper_b1 = nn.Linear(state_dim, mix_embed_dim)

        # Hypernetwork for second layer
        self.hyper_w2 = nn.Sequential(
            nn.Linear(state_dim, mix_embed_dim),
            nn.ReLU(),
            nn.Linear(mix_embed_dim, mix_embed_dim),
        )
        self.hyper_b2 = nn.Sequential(
            nn.Linear(state_dim, mix_embed_dim),
            nn.ReLU(),
            nn.Linear(mix_embed_dim, 1),
        )

        self.checkpoint_dir = os.path.join(os.path.dirname(os.path.realpath(__file__)), chkpt_dir)
        self.checkpoint_file = os.path.join(self.checkpoint_dir, 'qmix_mixer')
        self.device = T.device('cuda:0' if T.cuda.is_available() else 'cpu')
        self.to(self.device)

    def forward(self, agent_qs, states):
        """
        agent_qs: (batch, n_agents) - per-agent Q-values
        states: (batch, state_dim) - global state
        """
        bs = agent_qs.shape[0]

        # First layer: weights guaranteed non-negative via abs()
        w1 = T.abs(self.hyper_w1(states))  # (batch, mix_embed * n_agents)
        w1 = w1.view(bs, self.n_agents, -1)  # (batch, n_agents, mix_embed)
        b1 = self.hyper_b1(states)  # (batch, mix_embed)

        # (batch, 1, n_agents) @ (batch, n_agents, mix_embed) + (batch, 1, mix_embed)
        hidden = F.elu(T.bmm(agent_qs.unsqueeze(1), w1).squeeze(1) + b1)

        # Second layer
        w2 = T.abs(self.hyper_w2(states))  # (batch, mix_embed)
        b2 = self.hyper_b2(states)  # (batch, 1)

        # (batch, 1, mix_embed) @ (batch, mix_embed, 1) + (batch, 1)
        q_tot = T.bmm(hidden.unsqueeze(1), w2.unsqueeze(2)).squeeze(-1) + b2
        return q_tot

    def save_checkpoint(self):
        T.save(self.state_dict(), self.checkpoint_file)

    def load_checkpoint(self):
        self.load_state_dict(T.load(self.checkpoint_file))


class TargetQMIXMixer(QMIXMixer):
    """Target mixer."""
    def __init__(self, n_agents, state_dim, mix_embed_dim=32, chkpt_dir='tmp/ddpg'):
        super().__init__(n_agents, state_dim, mix_embed_dim, chkpt_dir)
        self.checkpoint_file = os.path.join(self.checkpoint_dir, 'target_qmix_mixer')
